// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFBYwzTN-Px7Bdk3uIs5bNx8eCocvPA4',
    appId: '1:1997708084:web:074ac924fbb268bc88a361',
    messagingSenderId: '1997708084',
    projectId: 'fir-auth-bf5dc',
    authDomain: 'fir-auth-bf5dc.firebaseapp.com',
    databaseURL: 'https://fir-auth-bf5dc-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-bf5dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZmi-LJRzu1P2AGafdxuAxAGvDaUBSTGA',
    appId: '1:1997708084:android:efb40ca9db0026e188a361',
    messagingSenderId: '1997708084',
    projectId: 'fir-auth-bf5dc',
    databaseURL: 'https://fir-auth-bf5dc-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-bf5dc.appspot.com',
  );

}